### ISSUE TITLE
please version hllpp

### ISSUE THREAD

**Issue by aviau** [retailnext/hllpp#2]
Hello,

Could you please tag this repository?

I am the Debian Maintainer for this project and tags would help Debian keep up with new releases/bugfixes.

See:
- http://semver.org/
- http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by psanford** [comment]
I pushed a tag for v1.0.0: https://github.com/retailnext/hllpp/tree/v1.0.0

**Comment by aviau** [comment]
thanks!
